const escape = (value) => String(value ?? '—').replace(/[&<>"']/g, (character) => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;' })[character]);
const shell = (title, body) => `<!doctype html><html lang="nl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escape(title)}</title><style>
*{box-sizing:border-box}body{margin:0;background:#0b0c0f;color:#f2efe8;font:15px system-ui,sans-serif}main{max-width:1200px;margin:auto;padding:24px}.brand{color:#d5ad58;letter-spacing:.12em}h1{font-size:clamp(28px,5vw,48px)}.cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(180px,1fr));gap:12px}.card,form.panel{background:#16181d;border:1px solid #2b2e35;border-radius:14px;padding:18px}.value{font-size:28px;font-weight:700}.muted{color:#9ca0aa}button,input{font:inherit;border-radius:9px;padding:11px 14px}button{background:#d5ad58;color:#14110a;border:0;font-weight:700;cursor:pointer}form.actions{display:flex;gap:8px;flex-wrap:wrap;margin:20px 0}table{width:100%;border-collapse:collapse;background:#16181d}th,td{padding:10px;border-bottom:1px solid #2b2e35;text-align:left}th{color:#d5ad58}.scroll{overflow:auto;border-radius:14px;border:1px solid #2b2e35}.error{color:#ff8989}.ok{color:#7fdca1}a{color:#d5ad58}@media(max-width:600px){main{padding:16px}th,td{white-space:nowrap;font-size:13px}}
</style></head><body><main>${body}</main></body></html>`;

export const loginView = (error = '') => shell('Koersplein beheer', `<p class="brand">KOERSPLEIN</p><h1>Beheer</h1><form class="panel" method="post" action="/beheer/login"><p class="error">${escape(error)}</p><p><label>Gebruikersnaam<br><input name="username" autocomplete="username" required></label></p><p><label>Wachtwoord<br><input name="password" type="password" autocomplete="current-password" required></label></p><button>Inloggen</button></form>`);

export function dashboardView(db, session, message = '') {
  const summary = db.prepare(`SELECT COUNT(*) total, SUM(CASE WHEN h.status='COMPLETE' THEN 1 ELSE 0 END) complete,
    SUM(CASE WHEN h.status='ERROR' THEN 1 ELSE 0 END) errors, SUM(h.record_count) records,
    MIN(h.first_available_date) earliest, MAX(h.last_available_date) latest, MAX(h.last_checked) lastChecked
    FROM instruments i JOIN history_status h ON h.instrument_id=i.id WHERE i.mic='XAMS' AND i.active=1`).get();
  const jobCounts = db.prepare(`SELECT SUM(CASE WHEN status IN ('QUEUED','RUNNING') THEN 1 ELSE 0 END) active,
    SUM(CASE WHEN status='COMPLETED' THEN 1 ELSE 0 END) complete,
    SUM(CASE WHEN status='COMPLETED_WITH_ERRORS' THEN 1 ELSE 0 END) errors FROM jobs`).get();
  const instruments = db.prepare(`SELECT i.company,i.ticker,i.isin,i.index_group,h.status,h.record_count,h.first_available_date,
    h.last_available_date,h.provider,h.last_checked,h.error FROM instruments i JOIN history_status h ON h.instrument_id=i.id WHERE i.mic='XAMS' ORDER BY i.company`).all();
  const jobs = db.prepare('SELECT * FROM jobs ORDER BY created_at DESC LIMIT 20').all();
  const action = (label, type) => `<button name="type" value="${type}">${label}</button>`;
  const instrumentRows = instruments.map((row) => `<tr><td>${escape(row.company)}</td><td>${escape(row.ticker)}</td><td>${escape(row.isin)}</td><td>${escape(row.index_group)}</td><td class="${row.status==='COMPLETE'?'ok':row.status==='ERROR'?'error':''}">${escape(row.status)}</td><td>${row.record_count}</td><td>${escape(row.first_available_date)}</td><td>${escape(row.last_available_date)}</td><td>${escape(row.provider)}</td><td>${escape(row.last_checked)}</td><td>${escape(row.error)}</td></tr>`).join('');
  const jobRows = jobs.map((job) => `<tr><td>${escape(job.type)}</td><td>${escape(job.status)}</td><td>${job.progress}/${job.total}</td><td>${job.success_count}</td><td>${job.failed_count}</td><td>${escape(job.created_at)}</td></tr>`).join('');
  return shell('Koersplein beheer', `<p class="brand">KOERSPLEIN BEHEER</p><h1>Amsterdam</h1><p class="muted">${escape(message)}</p><div class="cards"><div class="card"><div class="value">${summary.total}</div><span>Aandelen</span></div><div class="card"><div class="value">${summary.complete || 0}</div><span>Historie compleet</span></div><div class="card"><div class="value">${summary.total-(summary.complete||0)-(summary.errors||0)}</div><span>Nog te vullen</span></div><div class="card"><div class="value">${summary.errors || 0}</div><span>Fouten</span></div><div class="card"><div class="value">${summary.records || 0}</div><span>Koersdagen</span></div></div>
  <form class="actions" method="post" action="/beheer/jobs"><input type="hidden" name="csrf" value="${escape(session.csrf)}">${action('Controleer Amsterdam','CHECK_AMSTERDAM')}${action('Vul ontbrekende historie','HISTORY_BACKFILL')}${action('Werk dagkoersen bij','DAILY_UPDATE')}${action('Herstel mislukte aandelen','REPAIR_MISSING')}${action('Valideer historie','VALIDATE_HISTORY')}</form>
  <h2>Jobs</h2><p class="muted">Actief ${jobCounts.active||0} · klaar ${jobCounts.complete||0} · met fouten ${jobCounts.errors||0}</p><div class="scroll"><table><thead><tr><th>Type</th><th>Status</th><th>Voortgang</th><th>Gelukt</th><th>Fout</th><th>Gemaakt</th></tr></thead><tbody>${jobRows}</tbody></table></div>
  <h2>Status per aandeel</h2><p class="muted">Vroegste ${escape(summary.earliest)} · laatste handelsdag ${escape(summary.latest)} · laatste controle ${escape(summary.lastChecked)}</p><div class="scroll"><table><thead><tr><th>Bedrijf</th><th>Ticker</th><th>ISIN</th><th>Index</th><th>Status</th><th>Records</th><th>Eerste</th><th>Laatste</th><th>Provider</th><th>Controle</th><th>Fout</th></tr></thead><tbody>${instrumentRows}</tbody></table></div>
  <form method="post" action="/beheer/logout" style="margin-top:20px"><input type="hidden" name="csrf" value="${escape(session.csrf)}"><button>Uitloggen</button></form>`);
}
