const qs=(s,r=document)=>r.querySelector(s);const esc=v=>String(v??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
const state={shares:[],groups:[],activeGroup:'all',apiBaseUrl:'',prices:new Map()};
const money=(v,c='EUR')=>Number.isFinite(Number(v))?new Intl.NumberFormat('nl-NL',{style:'currency',currency:c,minimumFractionDigits:2,maximumFractionDigits:2}).format(Number(v)):'—';
const load=async p=>{const r=await fetch(p);if(!r.ok)throw new Error(`${p} kon niet worden geladen`);return r.json();};
const inGroup=(id,items=state.shares)=>id==='other'?items.filter(s=>!s.index):items.filter(s=>s.index===id);
const filtered=()=>{const q=qs('#search').value.trim().toLocaleLowerCase('nl');return state.shares.filter(s=>!q||[s.name,s.symbol,s.isin].some(v=>v.toLocaleLowerCase('nl').includes(q)));};
function table(items){return `<div class="table-wrap"><table><thead><tr><th>Bedrijf</th><th>Ticker</th><th>ISIN</th><th class="price">Open</th><th class="price">Slot</th><th></th></tr></thead><tbody>${items.map(s=>{const p=state.prices.get(s.isin);return `<tr><td><a class="share-link" href="share.html?isin=${encodeURIComponent(s.isin)}">${esc(s.name)}</a></td><td><span class="ticker">${esc(s.symbol)}</span></td><td>${esc(s.isin)}</td><td class="price">${p?money(p.open,p.currency):'—'}</td><td class="price">${p?money(p.close,p.currency):'—'}</td><td><a class="row-arrow" href="share.html?isin=${encodeURIComponent(s.isin)}">→</a></td></tr>`}).join('')}</tbody></table></div>`;}
function render(){const f=filtered();qs('#share-count').textContent=f.length;const cards=[{id:'all',label:'Alle',description:'Volledige markt'},...state.groups];qs('#index-navigation').innerHTML=cards.map(g=>`<button class="index-card${state.activeGroup===g.id?' selected':''}" type="button" data-group="${g.id}"><span>${esc(g.label)}</span><strong>${g.id==='all'?f.length:inGroup(g.id,f).length}</strong><small>${esc(g.description)}</small></button>`).join('');const visible=state.activeGroup==='all'?state.groups:state.groups.filter(g=>g.id===state.activeGroup);qs('#share-groups').innerHTML=visible.map(g=>{const items=inGroup(g.id,f);return `<section class="share-group"><header><div><p>${esc(g.kicker)}</p><h3>${esc(g.label)}</h3></div><span>${items.length} aandelen</span></header>${items.length?table(items):'<p class="empty-state">Geen aandelen gevonden.</p>'}</section>`}).join('');}
async function prices(){if(!state.apiBaseUrl)return;const manifest=await load(`${state.apiBaseUrl}/api/history/manifest.json`);const available=new Set(Object.keys(manifest.instruments||{}));const shares=state.shares.filter(s=>available.has(s.isin));let cursor=0,timer=null;const schedule=()=>{if(timer)return;timer=setTimeout(()=>{timer=null;render()},100)};async function worker(){while(cursor<shares.length){const s=shares[cursor++];try{const h=await load(`${state.apiBaseUrl}/api/history/${encodeURIComponent(s.isin)}`),bars=Array.isArray(h.bars)?h.bars:[],p=bars[bars.length-1];if(p){state.prices.set(s.isin,{date:p.date,open:p.open,close:p.close,currency:h.instrument?.currency||'EUR'});schedule();}}catch{}}}await Promise.all(Array.from({length:Math.min(4,shares.length)},worker));if(timer)clearTimeout(timer);render();}
qs('#index-navigation').addEventListener('click',e=>{const b=e.target.closest('[data-group]');if(b){state.activeGroup=b.dataset.group;render();}});qs('#search').addEventListener('input',render);
Promise.all([load('data/euronext-brussels.json'),load('data/euronext-brussels-indices.json'),load('data/runtime-config.json')]).then(([shares,indices,config])=>{const membership=new Map(indices.indices.flatMap(i=>i.constituents.map(m=>[m.isin,i.id])));state.shares=shares.shares.map(s=>({...s,index:membership.get(s.isin)||null}));state.groups=[...indices.indices.map(i=>({id:i.id,label:i.displayName,description:i.description,kicker:'Officiële Euronext-index'})),{id:'other',label:'Overig',description:'Buiten BEL 20, BEL Mid en BEL Small',kicker:'Overige Brusselse noteringen'}];state.apiBaseUrl=String(config.apiBaseUrl||'').replace(/\/$/,'');qs('#source-date').textContent=`Aandelen ${new Intl.DateTimeFormat('nl-NL',{dateStyle:'medium'}).format(new Date(shares.retrievedAt))} · indices ${new Intl.DateTimeFormat('nl-NL',{dateStyle:'medium'}).format(new Date(indices.asOf))}`;render();prices().catch(()=>{});}).catch(e=>{qs('#share-groups').innerHTML=`<p class="empty-state">${esc(e.message)}.</p>`;});