import fs from 'node:fs/promises';import path from 'node:path';import {spawnSync} from 'node:child_process';
const root=process.cwd(),issues=[],stats={js:0,json:0,workflows:0};
async function walk(d){let out=[];for(const e of await fs.readdir(d,{withFileTypes:true})){if(['.git','node_modules'].includes(e.name))continue;const p=path.join(d,e.name);out.push(...(e.isDirectory()?await walk(p):[p]))}return out}
const files=await walk(root);
for(const f of files){const rel=path.relative(root,f).replaceAll('\\','/');if(/\.(mjs|js)$/.test(rel)){stats.js++;const r=spawnSync(process.execPath,['--check',f],{encoding:'utf8'});if(r.status!==0)issues.push({severity:'ERROR',type:'JS_SYNTAX',file:rel,detail:(r.stderr||r.stdout).trim().slice(0,500)})}if(rel.endsWith('.json')){stats.json++;try{JSON.parse(await fs.readFile(f,'utf8'))}catch(e){issues.push({severity:'ERROR',type:'JSON_PARSE',file:rel,detail:e.message})}}if(rel.startsWith('.github/workflows/')&&/\.ya?ml$/.test(rel)){stats.workflows++;const c=await fs.readFile(f,'utf8');if(c.includes('\\n        run:'))issues.push({severity:'ERROR',type:'WORKFLOW_LITERAL_ESCAPE',file:rel,detail:'letterlijke \\n vóór run'});if(/schedule:\s*\n/.test(c))issues.push({severity:'INFO',type:'SCHEDULED_WORKFLOW',file:rel});}}
const workflowNames=new Map();for(const f of files.filter(x=>path.relative(root,x).replaceAll('\\','/').startsWith('.github/workflows/')&&/\.ya?ml$/.test(x))){const rel=path.relative(root,f).replaceAll('\\','/'),body=await fs.readFile(f,'utf8'),name=(body.match(/^name:\s*(.+)$/m)||[])[1]?.trim();if(name)workflowNames.set(name,rel);}
for(const f of files.filter(x=>path.relative(root,x).replaceAll('\\','/').startsWith('.github/workflows/')&&/\.ya?ml$/.test(x))){const rel=path.relative(root,f).replaceAll('\\','/'),body=await fs.readFile(f,'utf8');for(const block of body.matchAll(/workflow_run:\s*\n\s+workflows:\s*\[([^\]]+)\]/g)){for(const raw of block[1].split(',')){const target=raw.trim().replace(/^['"]|['"]$/g,'');if(target&&!workflowNames.has(target))issues.push({severity:'ERROR',type:'STALE_WORKFLOW_RUN_TARGET',file:rel,detail:target});}}}
const forbiddenFill=['world-fill-controller.yml','market-handoff-controller.yml','milan-fill.yml','oslo-source-first-fill.yml'];for(const n of forbiddenFill){if(files.some(x=>path.relative(root,x).replaceAll('\\','/')==='.github/workflows/'+n))issues.push({severity:'ERROR',type:'SUPERSEDED_FILL_ROUTE_PRESENT',file:'.github/workflows/'+n});}
try{const p=JSON.parse(await fs.readFile(path.join(root,'data/world-fill-plan.json'),'utf8'));for(const m of p.markets||[]){if(m.state==='BLOCKED'&&!m.blockedReason)issues.push({severity:'ERROR',type:'BLOCKED_WITHOUT_REASON',file:'data/world-fill-plan.json',detail:m.mic});}}catch{}
const activeLegacy=['model-arena-continuous.yml','autonomous-research-director.yml'];for(const n of activeLegacy){const f=path.join(root,'.github/workflows',n);try{const c=await fs.readFile(f,'utf8');if(/schedule:\s*\n/.test(c))issues.push({severity:'ERROR',type:'LEGACY_AUTOMATION_ACTIVE',file:'.github/workflows/'+n})}catch{}}
const report={generatedAt:new Date().toISOString(),stats,errors:issues.filter(x=>x.severity==='ERROR').length,warnings:issues.filter(x=>x.severity==='WARN').length,info:issues.filter(x=>x.severity==='INFO').length,issues};
await fs.mkdir('research/output/audit',{recursive:true});await fs.writeFile('research/output/audit/codebase-audit.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));if(report.errors)process.exitCode=2;
