const mean=a=>a.length?a.reduce((x,y)=>x+y,0)/a.length:null;
export function joinForecastOutcomes(forecasts,outcomes){const m=new Map(outcomes.map(o=>[[o.isin,o.cutoff,o.horizon_months,o.target_pct].join('|'),o]));return forecasts.map(f=>({...f,outcome:m.get([f.isin,f.cutoff,f.horizon_months,f.target_pct].join('|'))||null})).filter(x=>x.outcome);}
export function hindsightDiagnostics(rows){const names=['return_21d_pct','return_63d_pct','return_126d_pct','return_252d_pct','distance_1y_high_pct','distance_1y_low_pct'];const diagnostics=[];
 for(const name of names){const usable=rows.filter(r=>Number.isFinite(r.features?.[name]));if(usable.length<20)continue;const sorted=[...usable].sort((a,b)=>a.features[name]-b.features[name]);const groups=[sorted.slice(0,Math.floor(sorted.length/3)),sorted.slice(Math.floor(sorted.length*2/3))];const stats=groups.map(g=>({n:g.length,hit_rate:mean(g.map(x=>x.outcome.target_hit?1:0)),avg_return_pct:mean(g.map(x=>x.outcome.end_return_pct))}));diagnostics.push({feature:name,low:stats[0],high:stats[1],hit_rate_spread:(stats[1].hit_rate??0)-(stats[0].hit_rate??0)});}
 return diagnostics.sort((a,b)=>Math.abs(b.hit_rate_spread)-Math.abs(a.hit_rate_spread));
}
export function deriveCandidateRule(diagnostics,{minSamples=30,minSpread=.05}={}){const d=diagnostics.find(x=>x.low.n>=minSamples&&x.high.n>=minSamples&&Math.abs(x.hit_rate_spread)>=minSpread);if(!d)return null;return {feature:d.feature,direction:d.hit_rate_spread>0?'HIGH':'LOW',observed_spread:d.hit_rate_spread,status:'HYPOTHESIS_ONLY'};}
export function evaluateRule(rows,rule){if(!rule)return {n:0,selected:0,hit_rate:null,base_rate:null,lift:null};const usable=rows.filter(r=>Number.isFinite(r.features?.[rule.feature]));if(!usable.length)return {n:0,selected:0,hit_rate:null,base_rate:null,lift:null};const vals=usable.map(r=>r.features[rule.feature]).sort((a,b)=>a-b),cut=vals[Math.floor(vals.length*(rule.direction==='HIGH'?2/3:1/3))];const selected=usable.filter(r=>rule.direction==='HIGH'?r.features[rule.feature]>=cut:r.features[rule.feature]<=cut);const base=mean(usable.map(x=>x.outcome.target_hit?1:0)),hit=mean(selected.map(x=>x.outcome.target_hit?1:0));return {n:usable.length,selected:selected.length,threshold:cut,hit_rate:hit,base_rate:base,lift:hit===null||base===null?null:hit-base};}
export function validateOnUnseen(rows,splits,rule){const train=rows.filter(r=>r.cutoff<splits[r.isin].validation_end),test=rows.filter(r=>r.cutoff>=splits[r.isin].test_start);return {development:evaluateRule(train,rule),unseen:evaluateRule(test,rule),pass:!!rule&&test.length>=30&&evaluateRule(test,rule).lift>0};}
